version: '3'
volumes:
  skillstring_data:
    external: true
services:
  app:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    links:
      - database
      - redis
    volumes:
      - /usr/app/node_modules
      - ../../:/usr/app
    ports:
      - '5000:5000'
    env_file:
      - ../../.env
    environment:
      - PORT=5000
      - DATABASE_URL=mongodb://mongo:27017/pdf-documents-db
      - REDIS_URL=redis://redis
    entrypoint:
      - /usr/app/docker/dev/entrypoint.sh
    command:
      - yarn
      - entrypoint
    depends_on:
      - database
      - redis
  database:
    image: mongo
    container_name: mongo
    volumes:
      - skillstring_data:/data/mongodb
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
