image: docker:18.09.7

stages:
  - build
  - deploy

services:
  - docker:18.09.7-dind

before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli

build:
  stage: build
  image:
    name: docker/compose:1.21.2
    entrypoint: ["/bin/sh", "-c"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_FILE: docker/release/docker-compose.yml
  script:
    - $(aws ecr get-login --no-include-email --region eu-west-2)
    - docker volume create --name=skillstring_data > /dev/null
    - docker-compose -f $DOCKER_FILE build app
    - docker-compose -f $DOCKER_FILE push
  only:
    - branches

deploy_staging:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apk update && apk add openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - chmod 700 ~/.ssh
  script:
    - ssh $STAGING_SERVER "ls && cd ~/pdf-highlight-api && git stash && git fetch --all && git reset --hard origin/staging && yarn && pm2 restart yarn && exit"
  environment:
    name: staging
  only:
    - staging

deploy_production:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apk update && apk add openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_PROD" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - chmod 700 ~/.ssh
  script:
    - ssh $PROD_SERVER "cd ~/pdf-highlight-api && git stash && git fetch --all && git reset --hard origin/master && yarn && pm2 restart yarn && exit"
  environment:
    name: production
  only:
    - master
